apiVersion: v1
kind: Service
metadata:
  name: marketplace
  labels:
    run: marketplace
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    run: marketplace
